version: "3.4"
configs:
  postgres_exporter_config:
    file: ./queries.yaml
services:
  postgres-exporter-pgserver:
    image: quay.io/prometheuscommunity/postgres-exporter:v0.11.1
    configs:
      - source: postgres_exporter_config
        target: /etc/postgres_exporter/queries.yaml
    ports:
      - 9187:9187
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - DATA_SOURCE_NAME=postgresql://username:password@hostname:5432/postgres?sslmode=disable
      - PG_EXPORTER_EXTEND_QUERY_PATH=/etc/postgres_exporter/queries.yaml
